# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and Deploy ASP.Net Core App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build --configuration Release

      - name: Publish the application
        run: dotnet publish --configuration Release --output ./publish

      - name: Zip the published files using PowerShell
        shell: pwsh
        run: Compress-Archive -Path ./publish/* -DestinationPath ./publish.zip

      - name: Upload the publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish-artifact
          path: ./publish.zip

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download publish artifact
        uses: actions/download-artifact@v4
        with:
          name: publish-artifact

      - name: Deploy to Azure Web App using Publish Profile
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ECommerceLearningApp' # Your Azure App Service name
          slot-name: 'Production' # Change this if using deployment slots
          package: './publish.zip'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
